updating

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -48,22 +48,43 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/techflow-app:${{ github.sha }}
 
-      - name: Setup SSH Key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
-          chmod 600 ~/.ssh/ec2_key.pem
+  deploy-to-ec2:
+        needs: build-and-deploy
+        runs-on: ubuntu-latest
 
-      - name: Add EC2 to known hosts
-        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+        steps:
+            - name: Deploy to EC2
+              uses: appleboy/ssh-action@v1.0.3
+              with:
+                host: ${{ secrets.EC2_HOST }}
+                username: ${{ secrets.EC2_USER }}
+                key: ${{ secrets.EC2_SSH_KEY }}
 
-      - name: Deploy to EC2
-        run: |
-          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/techflow-app:${{ github.sha }}
-            docker stop techflow-app || true
-            docker rm techflow-app || true
-            docker run -d --name techflow-app -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/techflow-app:${{ github.sha }}
-            docker image prune -f
-          EOF
-        
+                script: |
+                    docker pull ${{ secrets.DOCKERHUB_USERNAME}}/techflow-api:latest
+                    docker stop techflow-api || true
+                    docker rm techflow-api || true
+
+                    docker run -d \
+                        --name techflow-api \
+                        -p 3000:3000 \
+                        ${{ secrets.DOCKERHUB_USERNAME}}/techflow-api:latest
+
+                    sleep 15
+
+                    docker exec techflow-api /app/scripts/health-check.sh
+
+                    if [ $? -ne 0 ]; then
+                        echo "Health check failed. Starting rollback..."
+                        
+                        docker stop techflow-api || true
+                        docker rm techflow-api || true
+
+                        docker pull ${{ secrets.DOCKERHUB_USERNAME}}/techflow-api:previous
+
+                        docker run -d --name techflow-api -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME}}/techflow-api:previous
+
+                        echo "Rollback Successful"
+                    fi
+
+                    echo "Deployment Successful" 
